### ISSUE TITLE
Projeto 1, Não  consigo alimentar o canal no thingspeak

### ISSUE THREAD

**Issue by rafalh1234567** [AquilesBurlamaqui/InternetDasCoisas#4]

**Comment by jilcimar** [comment]
@rafalh1234567 , não sei se ainda está com a dúvida ou já resolveu... 
Mas aperte a tecla F12, abra o console e coloque um print aqui... 
Outra coisa, teste com esse     

`<iframe width="450" height="260" style="border: 1px solid #cccccc;" src="https://thingspeak.com/channels/709912/charts/1?bgcolor=%23ffffff&color=%23d62020&dynamic=true&results=60&title=Sensor+LUX&type=line"></iframe>`

Se funcionar você vai e modifica só pela sua URl, preste atenção no endereço da URL se você não está copiando errado.
